<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SoalPenjajakanSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('soal_penjajakan')->truncate();

        $soal = [
            // ─────────────────────────────────────────────────────────────────
            // FRONTEND (10 Soal: 3 Beginner, 4 Intermediate, 3 Advanced)
            // ─────────────────────────────────────────────────────────────────
            
            // --- BEGINNER (Score: 5-10) ---
            [
                'jalur'      => 'frontend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'beginner',
                'pertanyaan' => 'Manakah elemen HTML yang benar untuk menyisipkan baris baru (line break)?',
                'kode_pertanyaan' => null,
                'opsi_a'     => '<lb>',
                'opsi_b'     => '<break>',
                'opsi_c'     => '<br>',
                'opsi_d'     => '<new>',
                'jawaban_benar' => 'c',
                'kata_kunci_jawaban' => null,
                'penjelasan' => 'Tag <br> digunakan untuk membuat baris baru tanpa memulai paragraf baru.',
                'bobot_skor' => 5,
                'urutan'     => 1,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'frontend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'beginner',
                'pertanyaan' => 'Apa output dari: console.log(1 + "1" - 1)?',
                'kode_pertanyaan' => 'console.log(1 + "1" - 1);',
                'opsi_a'     => '11',
                'opsi_b'     => '10',
                'opsi_c'     => '1',
                'opsi_d'     => 'NaN',
                'jawaban_benar' => 'b',
                'kata_kunci_jawaban' => null,
                'penjelasan' => '1 + "1" menjadi string "11", lalu "11" - 1 melakukan konversi numerik menjadi 10.',
                'bobot_skor' => 10,
                'urutan'     => 2,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'frontend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'beginner',
                'pertanyaan' => 'Property CSS mana yang digunakan untuk mengontrol spasi antar huruf (character spacing)?',
                'kode_pertanyaan' => null,
                'opsi_a'     => 'word-spacing',
                'opsi_b'     => 'letter-spacing',
                'opsi_c'     => 'text-spacing',
                'opsi_d'     => 'font-spacing',
                'jawaban_benar' => 'b',
                'kata_kunci_jawaban' => null,
                'penjelasan' => 'letter-spacing mengatur jarak antar karakter, sedangkan word-spacing mengatur jarak antar kata.',
                'bobot_skor' => 5,
                'urutan'     => 3,
                'aktif'      => true,
            ],

            // --- INTERMEDIATE (Score: 10-15) ---
            [
                'jalur'      => 'frontend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'intermediate',
                'pertanyaan' => 'Dalam JavaScript, apa fungsi dari `Object.freeze()`?',
                'kode_pertanyaan' => null,
                'opsi_a'     => 'Menghapus semua properti dari objek',
                'opsi_b'     => 'Membuat objek tidak dapat diubah (immutable), tidak bisa tambah/hapus/ubah properti',
                'opsi_c'     => 'Menyembunyikan objek dari debugger',
                'opsi_d'     => 'Mengompresi objek untuk menghemat memori',
                'jawaban_benar' => 'b',
                'kata_kunci_jawaban' => null,
                'penjelasan' => 'Object.freeze() mencegah perubahan apapun pada objek yang sudah ada.',
                'bobot_skor' => 10,
                'urutan'     => 4,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'frontend',
                'tipe'       => 'kode',
                'difficulty_level' => 'intermediate',
                'pertanyaan' => 'Perhatikan kode JavaScript berikut (Closure). Apa output yang dihasilkan?',
                'kode_pertanyaan' => "function buatCounter() {\n  let count = 0;\n  return function() {\n    return ++count;\n  };\n}\nconst c = buatCounter();\nc();\nconsole.log(c());",
                'opsi_a'     => '',
                'opsi_b'     => '',
                'opsi_c'     => '',
                'opsi_d'     => '',
                'jawaban_benar' => '2',
                'kata_kunci_jawaban' => '2',
                'penjelasan' => 'Panggilan pertama c() mengubah count jadi 1, panggilan kedua mengubahnya jadi 2 dan mengembalikannya.',
                'bobot_skor' => 15,
                'urutan'     => 5,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'frontend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'intermediate',
                'pertanyaan' => 'Manakah unit CSS yang nilainya relatif terhadap ukuran font dari elemen root (<html>)?',
                'kode_pertanyaan' => null,
                'opsi_a'     => 'em',
                'opsi_b'     => 'rem',
                'opsi_c'     => 'vh',
                'opsi_d'     => 'px',
                'jawaban_benar' => 'b',
                'kata_kunci_jawaban' => null,
                'penjelasan' => 'rem (Root EM) relatif terhadap font-size elemen root. em relatif terhadap font-size elemen induknya.',
                'bobot_skor' => 10,
                'urutan'     => 6,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'frontend',
                'tipe'       => 'kode',
                'difficulty_level' => 'intermediate',
                'pertanyaan' => 'Gunakan Fetch API untuk mengambil data dari URL "https://api.example.com/data". Tuliskan baris kode untuk mengubah response menjadi format JSON.',
                'kode_pertanyaan' => "fetch('https://api.example.com/data')\n  .then(response => response._______());",
                'opsi_a'     => '',
                'opsi_b'     => '',
                'opsi_c'     => '',
                'opsi_d'     => '',
                'jawaban_benar' => 'json',
                'kata_kunci_jawaban' => 'json',
                'penjelasan' => 'Method response.json() digunakan untuk mengekstrak body JSON dari object response Fetch.',
                'bobot_skor' => 15,
                'urutan'     => 7,
                'aktif'      => true,
            ],

            // --- ADVANCED (Score: 15-20) ---
            [
                'jalur'      => 'frontend',
                'tipe'       => 'kode',
                'difficulty_level' => 'advanced',
                'pertanyaan' => 'Implementasikan fungsi sederhana `kuadrat` menggunakan arrow function dalam satu baris yang menerima parameter `n` dan mengembalikan nilai kuadratnya.',
                'kode_pertanyaan' => "// Contoh: kuadrat(4) => 16\nconst kuadrat = _______ => _______;",
                'opsi_a'     => '',
                'opsi_b'     => '',
                'opsi_c'     => '',
                'opsi_d'     => '',
                'jawaban_benar' => 'n => n * n',
                'kata_kunci_jawaban' => 'n * n',
                'penjelasan' => 'Arrow function satu baris memiliki implicit return.',
                'bobot_skor' => 15,
                'urutan'     => 8,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'frontend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'advanced',
                'pertanyaan' => 'Apa yang terjadi jika kita mencoba mengakses properti di `null` atau `undefined` tanpa optional chaining di JS modern?',
                'kode_pertanyaan' => null,
                'opsi_a'     => 'Mengembalikan undefined',
                'opsi_b'     => 'Mengembalikan null',
                'opsi_c'     => 'Melempar TypeError (Uncaught TypeError)',
                'opsi_d'     => 'Program berhenti diam-diam tanpa error',
                'jawaban_benar' => 'c',
                'kata_kunci_jawaban' => null,
                'penjelasan' => 'Mengakses properti dari non-object (null/undefined) akan menyebabkan error fatal TypeError.',
                'bobot_skor' => 15,
                'urutan'     => 9,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'frontend',
                'tipe'       => 'kode',
                'difficulty_level' => 'advanced',
                'pertanyaan' => 'Perhatikan array berikut: `const data = [{x:1}, {x:5}, {x:10}]`. Gunakan `reduce` untuk menjumlahkan semua nilai `x`. Tuliskan isi dari fungsi reduce-nya.',
                'kode_pertanyaan' => "const total = data.reduce((acc, curr) => _______, 0);",
                'opsi_a'     => '',
                'opsi_b'     => '',
                'opsi_c'     => '',
                'opsi_d'     => '',
                'jawaban_benar' => 'acc + curr.x',
                'kata_kunci_jawaban' => 'acc + curr.x',
                'penjelasan' => 'Fungsi reduce mengakumulasi nilai acc dengan nilai curr.x di setiap iterasi.',
                'bobot_skor' => 15,
                'urutan'     => 10,
                'aktif'      => true,
            ],


            // ─────────────────────────────────────────────────────────────────
            // BACKEND (10 Soal: 3 Beginner, 4 Intermediate, 3 Advanced)
            // ─────────────────────────────────────────────────────────────────

            // --- BEGINNER ---
            [
                'jalur'      => 'backend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'beginner',
                'pertanyaan' => 'HTTP status code manakah yang berarti "Not Found"?',
                'kode_pertanyaan' => null,
                'opsi_a'     => '200',
                'opsi_b'     => '403',
                'opsi_c'     => '404',
                'opsi_d'     => '500',
                'jawaban_benar' => 'c',
                'kata_kunci_jawaban' => null,
                'penjelasan' => '404 Not Found adalah kode standar jika resource yang diminta tidak ditemukan di server.',
                'bobot_skor' => 5,
                'urutan'     => 1,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'backend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'beginner',
                'pertanyaan' => 'Fungsi PHP manakah yang digunakan untuk mencetak teks ke browser?',
                'kode_pertanyaan' => null,
                'opsi_a'     => 'print()',
                'opsi_b'     => 'echo',
                'opsi_c'     => 'write()',
                'opsi_d'     => 'A dan B benar',
                'jawaban_benar' => 'd',
                'kata_kunci_jawaban' => null,
                'penjelasan' => 'Baik echo maupun print() dapat digunakan untuk output string di PHP.',
                'bobot_skor' => 5,
                'urutan'     => 2,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'backend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'beginner',
                'pertanyaan' => 'Apa simbol yang digunakan untuk memulai variabel di PHP?',
                'kode_pertanyaan' => null,
                'opsi_a'     => '&',
                'opsi_b'     => '#',
                'opsi_c'     => '$',
                'opsi_d'     => '@',
                'jawaban_benar' => 'c',
                'kata_kunci_jawaban' => null,
                'penjelasan' => 'Semua variabel di PHP harus diawali dengan tanda dollar ($).',
                'bobot_skor' => 5,
                'urutan'     => 3,
                'aktif'      => true,
            ],

            // --- INTERMEDIATE ---
            [
                'jalur'      => 'backend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'intermediate',
                'pertanyaan' => 'Manakah tipe JOIN SQL yang hanya mengembalikan baris yang memiliki kecocokan di kedua tabel?',
                'kode_pertanyaan' => null,
                'opsi_a'     => 'LEFT JOIN',
                'opsi_b'     => 'RIGHT JOIN',
                'opsi_c'     => 'INNER JOIN',
                'opsi_d'     => 'FULL JOIN',
                'jawaban_benar' => 'c',
                'kata_kunci_jawaban' => null,
                'penjelasan' => 'INNER JOIN mencari irisan (intersection) data yang ada di kedua tabel.',
                'bobot_skor' => 10,
                'urutan'     => 4,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'backend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'intermediate',
                'pertanyaan' => 'Apa tujuan dari menggunakan Middleware di Laravel?',
                'kode_pertanyaan' => null,
                'opsi_a'     => 'Mengatur layout tampilan (Blade)',
                'opsi_b'     => 'Menyaring (filter) HTTP request yang masuk ke aplikasi',
                'opsi_c'     => 'Menyimpan data ke database',
                'opsi_d'     => 'Mempercepat query database',
                'jawaban_benar' => 'b',
                'kata_kunci_jawaban' => null,
                'penjelasan' => 'Middleware bertindak sebagai mekanisme penyaring (misal: cek login) sebelum request sampai ke controller.',
                'bobot_skor' => 10,
                'urutan'     => 5,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'backend',
                'tipe'       => 'kode',
                'difficulty_level' => 'intermediate',
                'pertanyaan' => 'Lengkapi query SQL untuk mengambil 5 user terbaru berdasarkan tanggal dibuat.',
                'kode_pertanyaan' => "SELECT * FROM users\n_______ BY created_at _______\nLIMIT 5;",
                'opsi_a'     => '',
                'opsi_b'     => '',
                'opsi_c'     => '',
                'opsi_d'     => '',
                'jawaban_benar' => 'ORDER BY created_at DESC',
                'kata_kunci_jawaban' => 'order, desc',
                'penjelasan' => 'ORDER BY ... DESC digunakan untuk mengurutkan dari yang terbaru/terbesar.',
                'bobot_skor' => 15,
                'urutan'     => 6,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'backend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'intermediate',
                'pertanyaan' => 'Dalam arsitektur MVC, "Controller" bertanggung jawab untuk apa?',
                'kode_pertanyaan' => null,
                'opsi_a'     => 'Mendefinisikan skema database',
                'opsi_b'     => 'Menangani logika bisnis dan interaksi antara Model dan View',
                'opsi_c'     => 'Menampilkan data ke user (UI)',
                'opsi_d'     => 'Menyimpan konfigurasi server',
                'jawaban_benar' => 'b',
                'kata_kunci_jawaban' => null,
                'penjelasan' => 'Controller adalah jembatan yang memproses input user, memanggil model, dan mengirim data ke view.',
                'bobot_skor' => 10,
                'urutan'     => 7,
                'aktif'      => true,
            ],

            // --- ADVANCED ---
            [
                'jalur'      => 'backend',
                'tipe'       => 'kode',
                'difficulty_level' => 'advanced',
                'pertanyaan' => 'Tuliskan method Eloquent Laravel untuk mengambil data User yang memiliki id = 1, namun lemparkan error 404 otomatis jika tidak ditemukan.',
                'kode_pertanyaan' => "User::_______(1);",
                'opsi_a'     => '',
                'opsi_b'     => '',
                'opsi_c'     => '',
                'opsi_d'     => '',
                'jawaban_benar' => 'findOrFail',
                'kata_kunci_jawaban' => 'findorfail',
                'penjelasan' => 'findOrFail() adalah shortcut praktis di Laravel untuk mencari id atau auto-abort 404.',
                'bobot_skor' => 15,
                'urutan'     => 8,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'backend',
                'tipe'       => 'pilihan_ganda',
                'difficulty_level' => 'advanced',
                'pertanyaan' => 'Apa itu "SQL Injection" dan bagaimana cara terbaik mencegahnya di Laravel?',
                'kode_pertanyaan' => null,
                'opsi_a'     => 'Teknik mencuri password, dicegah dengan hash md5',
                'opsi_b'     => 'Manipulasi query database melalui input user, dicegah dengan Eloquent atau Query Builder (Parameterized Queries)',
                'opsi_c'     => 'Cara mempercepat query, dicegah dengan cache',
                'opsi_d'     => 'Error saat database penuh, dicegah dengan upgrade RAM',
                'jawaban_benar' => 'b',
                'kata_kunci_jawaban' => null,
                'penjelasan' => 'Eloquent menggunakan PDO parameter binding yang secara otomatis membersihkan input dari karakter berbahaya.',
                'bobot_skor' => 15,
                'urutan'     => 9,
                'aktif'      => true,
            ],
            [
                'jalur'      => 'backend',
                'tipe'       => 'kode',
                'difficulty_level' => 'advanced',
                'pertanyaan' => 'Perhatikan kode PHP berikut (Dependency Injection). Apa nama konsep ketika class menerima object lain melalui constructor?',
                'kode_pertanyaan' => "class UserRepo {\n  public function __construct(Database \$db) {\n    \$this->db = \$db;\n  }\n}",
                'opsi_a'     => '',
                'opsi_b'     => '',
                'opsi_c'     => '',
                'opsi_d'     => '',
                'jawaban_benar' => 'Dependency Injection',
                'kata_kunci_jawaban' => 'dependency injection',
                'penjelasan' => 'DI adalah pola desain di mana sebuah objek menerima objek lain yang dibutuhkannya (dependensinya).',
                'bobot_skor' => 20,
                'urutan'     => 10,
                'aktif'      => true,
            ],
        ];

        // Tambahkan timestamps
        $now = now();
        foreach ($soal as &$s) {
            $s['created_at'] = $now;
            $s['updated_at'] = $now;
        }

        DB::table('soal_penjajakan')->insert($soal);

        $this->command->info('✅ 20 soal penjajakan (Beginner, Intermediate, Advanced) berhasil di-seed!');
    }
}
